-- Conquest: Ascension beta requests. This migration belongs in the Conquest
-- Supabase project, not the Intelligent Decisions / CourierIQ project.

create table if not exists public.beta_access_requests (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(name) between 1 and 80),
    email text not null unique check (
        email = lower(btrim(email))
        and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
    ),
    android_device text not null check (char_length(android_device) between 1 and 120),
    testing_focus text not null check (char_length(testing_focus) between 1 and 1200),
    status text not null default 'pending' check (
        status in ('pending', 'approved', 'invited', 'active', 'declined')
    ),
    email_status text not null default 'pending' check (
        email_status in ('pending', 'sent', 'failed')
    ),
    resend_email_id text,
    admin_email_status text not null default 'pending' check (
        admin_email_status in ('pending', 'sent', 'failed')
    ),
    admin_resend_id text,
    invite_email_status text not null default 'not_sent' check (
        invite_email_status in ('not_sent', 'pending', 'sent', 'failed')
    ),
    invite_resend_id text,
    last_email_error text,
    admin_notes text not null default '' check (char_length(admin_notes) <= 5000),
    reviewed_at timestamptz,
    reviewed_by text,
    invited_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists beta_access_requests_status_created_idx
on public.beta_access_requests (status, created_at desc);

create table if not exists public.beta_access_request_events (
    id bigint generated by default as identity primary key,
    request_id bigint not null references public.beta_access_requests(id) on delete cascade,
    event_type text not null,
    actor_email text not null,
    previous_status text,
    new_status text,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists beta_access_request_events_request_created_idx
on public.beta_access_request_events (request_id, created_at desc);

alter table public.beta_access_requests enable row level security;
alter table public.beta_access_request_events enable row level security;

-- No anonymous policies are created. The Cloudflare Worker uses the private
-- SUPABASE_SECRET_KEY and is the sole public write/read path.
